import { Player } from './player';

export const PLAYERS: Player[] = [
    {
        playername: '佐々木希',
        number: 31,
        position: '1203',
        nationality: '日本',
    },
    {
        playername: '佐藤洋子',
        number: 32,
        position: '1800',
        nationality: '日本',
    },  
    {
        playername: '二本柳子',
        number: 33,
        position: '1200',
        nationality: '別の',
    },  
    {
        playername: '高橋晶子',
        number: 34,
        position: '1450',
        nationality: '日本',
    },  
    {
        playername: '篠田若夏',
        number: 35,
        position: '1400',
        nationality: '別の',
    },  
    {
        playername: '高橋葵子',
        number: 36,
        position: '2000',
        nationality: '日本',
    },  
    {
        playername: '下田遥子',
        number: 37,
        position: '3200',
        nationality: '別の',
    },  
    {
        playername: '篠田柳子',
        number: 38,
        position: '4200',
        nationality: '別の',
    },  
    {
        playername: '佐藤茜子',
        number: 39,
        position: '6700',
        nationality: '日本',
    },  
    {
        playername: '小林幸助',
        number: 10,
        position: '4500',
        nationality: '日本',
    },  
    {
        playername: '佐々木綾',
        number: 11,
        position: '1600',
        nationality: '日本',
    },  
    {
        playername: '高橋夏萌',
        number: 12,
        position: '5600',
        nationality: '別の',
    },  
    {
        playername: '窪田七彩',
        number:13,
        position: '1800',
        nationality: '日本',
    },  
    {
        playername: '高橋水蓮',
        number: 14,
        position: '8700',
        nationality: '別の',
    },  
    {
        playername: '羽生結弦',
        number: 15,
        position: '9200',
        nationality: '日本',
    },  
    {
        playername: '関根孝介',
        number: 16,
        position: '4500',
        nationality: '日本',
    },  
    {
        playername: '新垣结衣',
        number: 17,
        position: '1900',
        nationality: '別の',
    },
    {
        playername: '石原里美',
        number: 18,
        position: '1700',
        nationality: '日本',
    },  
  {
        playername: '桥本环奈',
        number: 19,
        position: '1600',
        nationality: '別の',
    },
    {
        playername: '吉泽明步',
        number: 20,
        position: '1300',
        nationality: '日本',
    },  
  {
        playername: '水咲萝拉',
        number: 21,
        position: '1500',
        nationality: '別の',
    },
    {
        playername: '大桥未久',
        number: 22,
        position: '1400',
        nationality: '日本',
    },  
  {
        playername: '花泽香菜',
        number: 23,
        position: '1200',
        nationality: '別の',
    },
    {
        playername: '佐佐木希',
        number: 24,
        position: '1100',
        nationality: '日本',
    },  
  {
        playername: '堀北真希',
        number: 25,
        position: '1000',
        nationality: '別の',
    },
    {
        playername: '酒井法子',
        number: 26,
        position: '1800',
        nationality: '日本',
    },  
  {
        playername: '工藤静香',
        number: 27,
        position: '1300',
        nationality: '別の',
    },
    {
        playername: '桐谷美玲',
        number: 28,
        position: '1500',
        nationality: '日本',
    },  
  {
        playername: '山口百惠',
        number: 29,
        position: '1700',
        nationality: '別の',
    },
    {
        playername: '北川景子',
        number: 30,
        position: '1200',
        nationality: '日本',
    },  
];